# GAME SETTINGS 
import math 

RES = WIDTH, HEIGHT = 1440, 900
# RES = WIDTH, HEIGHT = 800, 600
FPS = 60

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUMRAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20