# GAME SETTINGS 
import math 

RES = WIDTH, HEIGHT = 1440, 900
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 60

MOUSE_SENSITIVITY = 0.0003
MOUSE_RELATIVE_MOVEMENT = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT
MOUSE_BORDER_UP = 100
MOUSE_BORDER_DOWN = HEIGHT - MOUSE_BORDER_UP

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUMRAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DISTANCE = HALF_WIDTH // math.tan(HALF_FOV)

SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = 256 // 2